// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

public partial class Product
{
    public int IdProducto { get; set; }

    public string Nombre { get; set; }

    public string Categoria { get; set; }
}